# coding: utf-8

import ctypes
ctypes.cdll.LoadLibrary('./libcVector.so')
a = ctypes.cdll.LoadLibrary('./libcVector.so')
a.foo('BHSig260FIX/Hindi/001/H-S-1-F-01-H-S-1-G-01_tsmxor.tif')
b = ctypes.create_string_buffer('BHSig260FIX/Hindi/001/H-S-1-F-01-H-S-1-G-01_tsmxor.tif')
path = 'BHSig260FIX/Hindi/001/H-S-1-F-01-H-S-1-G-01_tsmxor.tif'
path
path.encode('UTF-8')
b = ctypes.create_string_buffer(path)
z = path.encode('UTF-8')
b = ctypes.create_string_buffer(z)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo.restype = ndpointer(dtype=ctypes.c_int, shape=(10,))
from numpy.ctypeslib import ndpointer
a.foo.restype = ndpointer(dtype=ctypes.c_int, shape=(10,))
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
a.foo(b)
get_ipython().run_line_magic('save', '')
get_ipython().run_line_magic('save', 'howtoLib')
